### ISSUE TITLE
A critical error occured.

### ISSUE THREAD

**Issue by ojt1998** [werwolf2303/SpotifyXP#10] opened 2023-04-12 10:14 UTC
Version 1.7 throws a box saying a critical error occured. Has to be exited through task manager. Prior to the error, shuffling wasn't working so I closed and reopened to try enabling shuffle before playing music at which point the app crashed. Tried deleting the appdata folder for SpotifyXP but the error still happens. Reverting back to 1.5 allows the app to function again.

**Comment by werwolf2303** [comment] 2023-04-12 16:29
Please open SpotifyXP in cmd with this argument: --setup-complete and send me what cmd says

**Comment by ojt1998** [comment] 2023-04-13 08:56
![Screenshot 2023-04-13 at 09 55 41](https://user-images.githubusercontent.com/53399413/231708264-672536ba-d5c4-4756-b3de-e936ae27e4bb.png)

This is the cmd output

**Comment by werwolf2303** [comment] 2023-04-13 10:46
It should be fixed now

**Comment by ojt1998** [comment] 2023-04-13 11:05
The critical error no longer appears but the app locks up and eventually a "Something went wrong" dialogue appears.
![Screenshot 2023-04-13 at 12 05 11](https://user-images.githubusercontent.com/53399413/231739976-020cfc60-7baa-43fe-b799-c50b588f082c.png)
![Screenshot 2023-04-13 at 12 04 10](https://user-images.githubusercontent.com/53399413/231739981-8f3c107b-fdd5-4494-8073-8e79dfbd969e.png)

**Comment by werwolf2303** [comment] 2023-04-13 11:07
can you send me the response of a ping request to : https://api.werwolf2303.de

**Comment by ojt1998** [comment] 2023-04-13 11:10
That gives an unknown host error

**Comment by ojt1998** [comment] 2023-04-13 11:11
IP appears as 91.2.149.224 but the request times out

**Comment by werwolf2303** [comment] 2023-04-13 11:14
It seems like my server behaves really weird when ping requests are being send. 
Try the newest nightly build I changed IOException to Exception

**Comment by werwolf2303** [comment] 2023-04-13 11:17
In which country do you live?

**Comment by ojt1998** [comment] 2023-04-13 12:20
Still the same issue and the UK

**Comment by werwolf2303** [comment] 2023-04-13 12:23
I can't reproduce this for some reason for me it works fine. That makes it difficult to fix this. Is this Virtual Machine or Real Hardware?

**Closed** 2023-04-16 10:47 UTC
Labels: bug
